INSERT INTO cfdis(clabe,using_description,person_restricted)
VALUES ('G01','Adquisición de mercancías',null),
('G01','Adquisición de mercancías',null),
('G02','Devoluciones, descuentos o bonificaciones',null),
('G03','Gastos en general',null),
('I01','Construcciones',null),
('I02','Mobilario y equipo de oficina por inversiones',null),
('I03','Equipo de transporte',null),
('I04','Equipo de computo y accesorios',null),
('I05','Dados, troqueles, moldes, matrices y herramental',null),
('I06','Comunicaciones telefónicas',null),
('I07','Comunicaciones satelitales',null),
('I08','Otra maquinaria y equipo',null),
('D01','Honorarios médicos, dentales y gastos hospitalarios.',2),
('D02','Gastos médicos por incapacidad o discapacidad',2),
('D03','Gastos funerales.',2),
('D04','Donativos.',2),
('D05','Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).',2),
('D06','Aportaciones voluntarias al SAR.',2),
('D07','Primas por seguros de gastos médicos.',2),
('D08','Gastos de transportación escolar obligatoria.',2),
('D09','Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.',2),
('D10','Pagos por servicios educativos (colegiaturas)',2),
('P01','Por definir',null);